import React from "react";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

interface CampaignInstructionsProps {
  selectedVoice: string;
  setSelectedVoice: (voice: string) => void;
  campaignInstructions: string;
  setCampaignInstructions: (instructions: string) => void;
}

const CampaignInstructions: React.FC<CampaignInstructionsProps> = ({
  selectedVoice = "indian-male",
  setSelectedVoice,
  campaignInstructions,
  setCampaignInstructions,
}) => {
  return (
    <div className="flex flex-col h-full min-h-0 bg-zinc-200 dark:bg-zinc-800 rounded-lg p-4">
      <div className="flex items-center gap-2 mb-4">
        <h2 className="text-lg font-semibold">Campaign Instructions</h2>
      </div>

      <div className="mb-4">
        <Select value={selectedVoice} onValueChange={setSelectedVoice}>
          <SelectTrigger>
            <SelectValue placeholder="Select voice" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="indian-male">
              <div className="flex items-center gap-2">
                <div className="h-6 w-6 rounded-full bg-primary/20 flex items-center justify-center">
                  <span className="sr-only">Indian Male Voice</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
                    <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                    <line x1="12" x2="12" y1="19" y2="22" />
                  </svg>
                </div>
                Indian Male Voice
              </div>
            </SelectItem>
            <SelectItem value="us-female">
              <div className="flex items-center gap-2">
                <div className="h-6 w-6 rounded-full bg-primary/20 flex items-center justify-center">
                  <span className="sr-only">US Female Voice</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
                    <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                    <line x1="12" x2="12" y1="19" y2="22" />
                  </svg>
                </div>
                US Female Voice
              </div>
            </SelectItem>
            <SelectItem value="uk-male">
              <div className="flex items-center gap-2">
                <div className="h-6 w-6 rounded-full bg-primary/20 flex items-center justify-center">
                  <span className="sr-only">UK Male Voice</span>
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="16"
                    height="16"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
                    <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
                    <line x1="12" x2="12" y1="19" y2="22" />
                  </svg>
                </div>
                UK Male Voice
              </div>
            </SelectItem>
          </SelectContent>
        </Select>
      </div>

      <div className="mb-2 flex justify-between items-center">
        <span className="text-xs text-muted-foreground">Generated by AI</span>
      </div>

      <div className="rounded-md border border-input flex-1">
        <Textarea
          className="w-full h-[450px] font-mono text-sm resize-none border-none rounded-none"
          value={campaignInstructions}
          onChange={(e) => setCampaignInstructions(e.target.value)}
        />
      </div>
    </div>
  );
};

export default CampaignInstructions;
